#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- 1. ユーザーの作成
    CREATE USER ${MIGRATION_USER} WITH PASSWORD '${MIGRATION_PASSWORD}';
    CREATE USER ${APP_USER} WITH PASSWORD '${APP_PASSWORD}';

    -- 2. DB接続権限の付与
    GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${MIGRATION_USER};
    GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${APP_USER};

    -- 3. スキーマの作成（所有者を MIGRATION_USER に設定）
    CREATE SCHEMA IF NOT EXISTS ${MIGRATION_SCHEMA} AUTHORIZATION ${MIGRATION_USER};
    CREATE SCHEMA IF NOT EXISTS ${APP_SCHEMA} AUTHORIZATION ${MIGRATION_USER};

    -- 4. search_path の設定
    ALTER ROLE ${MIGRATION_USER} SET search_path TO ${MIGRATION_SCHEMA}, ${APP_SCHEMA}, public;
    ALTER ROLE ${APP_USER} SET search_path TO ${APP_SCHEMA}, public;

    -- 5. アプリユーザーへの基本権限付与（APP_SCHEMA の使用許可）
    GRANT USAGE ON SCHEMA ${APP_SCHEMA} TO ${APP_USER};

    -- 6. DML・実行権限の自動付与
    ALTER DEFAULT PRIVILEGES FOR ROLE ${MIGRATION_USER} IN SCHEMA ${APP_SCHEMA}
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${APP_USER};
    ALTER DEFAULT PRIVILEGES FOR ROLE ${MIGRATION_USER} IN SCHEMA ${APP_SCHEMA}
        GRANT USAGE, SELECT ON SEQUENCES TO ${APP_USER};
    ALTER DEFAULT PRIVILEGES FOR ROLE ${MIGRATION_USER} IN SCHEMA ${APP_SCHEMA}
        GRANT EXECUTE ON FUNCTIONS TO ${APP_USER};
    ALTER DEFAULT PRIVILEGES FOR ROLE ${MIGRATION_USER} IN SCHEMA ${APP_SCHEMA}
        GRANT EXECUTE ON ROUTINES TO ${APP_USER};

EOSQL
