spring:
  application:
    name: app
  flyway:
    enabled: true
    url: ${MIGRATION_URL}
    user: ${MIGRATION_USER}
    password: ${MIGRATION_PASSWORD}
    schemas: ${APP_SCHEMA}
    placeholders:
      app-schema: ${APP_SCHEMA}
