#!/bin/bash
set -e

# 1. マイグレーション用ユーザー（DDL権限）の作成
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${MIGRATION_USER} WITH PASSWORD '${MIGRATION_PASSWORD}';
EOSQL

# 2. アプリケーション実行用ユーザー（DML権限）の作成
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${APP_USER} WITH PASSWORD '${APP_PASSWORD}';
EOSQL

# 3. マイグレーション用スキーマの作成
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE SCHEMA ${MIGRATION_SCHEMA};
EOSQL

# 4. アプリケーション用スキーマの作成
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE SCHEMA ${APP_SCHEMA};
EOSQL

# 5. 権限の設定
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    GRANT ALL ON SCHEMA ${MIGRATION_SCHEMA} TO ${MIGRATION_USER};
    GRANT ALL ON SCHEMA ${APP_SCHEMA} TO ${MIGRATION_USER};
    GRANT USAGE ON SCHEMA ${APP_SCHEMA} TO ${APP_USER};
    ALTER DEFAULT PRIVILEGES FOR ROLE ${MIGRATION_USER} IN SCHEMA ${APP_SCHEMA} GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${APP_USER};
    ALTER DEFAULT PRIVILEGES FOR ROLE ${MIGRATION_USER} IN SCHEMA ${APP_SCHEMA} GRANT USAGE, SELECT ON SEQUENCES TO ${APP_USER};
    ALTER DEFAULT PRIVILEGES FOR ROLE ${MIGRATION_USER} IN SCHEMA ${APP_SCHEMA} GRANT EXECUTE ON FUNCTIONS TO ${APP_USER};
    ALTER DEFAULT PRIVILEGES FOR ROLE ${MIGRATION_USER} IN SCHEMA ${APP_SCHEMA} GRANT EXECUTE ON ROUTINES TO ${APP_USER};
EOSQL
